### DISCUSSION TITLE
Remove the ".0" at the end of numbers & calculate with numbers

### DISCUSSION THREAD

**Discussion by wacholderpolka** [gickowtf/pixoo-homeassistant#11] [Q&A] [answered]
Hi, I just tried to make my own Pixoo screens with this nice project.
I added some values from my Fenecon system, but there is a problem, that the numbers of total energy consumption are given in Wh, but I wat to show just the kWh value.

- Is there any possibility to devide the sensor value by 100 (or do any calculation with it before displaying)?
- Is there a way to cut off the ".0" at the end of numbers so they are as short as possible?

I must admit, that I am quite new to the whole Homeassistant thing, so sorry if this is a stupid question:-)

**Comment by wacholderpolka** [comment, marked as answer]
Ok, after playing around a little bit, I found some ways to eliminate the .0 for my own screens, but not for the solar screen.
I solved the calculation issue by defining extra sensors in the configuration. yaml so this is working, too:-)

configuration.yaml:

```
sensor:
  - platform: template
    sensors:
        energie_verbrauch_kwh:
            friendly_name: "Energie-Verbrauch in kWh"
            unit_of_measurement: 'kWh'
            value_template: '{{ (states("sensor.FEMS_GridBuyActiveEnergy") |float // 1000)|int}}'

```
and then for the pixoo:

```
        - text: "{{ states.sensor.energie_verbrauch_kwh.state }}"
          position: [1, 8]
          font: FONT_GICKO
          font_color: [255, 0, 0]  # red
```

There is only the remaining issue, that the solar screen shows 100.0 for an int value of 100
