### DISCUSSION TITLE
Fully automation-based logic

### DISCUSSION THREAD

**Discussion by SB2DD** [gickowtf/pixoo-homeassistant#49] [Show and tell]
Alright, just to test, I tried implementing the whole "page rotation"+notification logic of the integration only with automations. Here is all the automations/scripts that allowed me to do it. Feel free to use this yourselves! 

(Also, the "List of pages" in the config was set to nothing.)

The Pixoo's page rotator loop **SCRIPT**. This is the replacement of "List of pages": (In my case it's referenced as script.1711740597910 in the other automations)
```yaml
alias: Pixoo Page Rotator Loop
sequence:
  - repeat:
      while:
        - condition: template
          value_template: "{{true}}"
      sequence:
        - service: divoom_pixoo.show_message
          metadata: {}
          data:
            page_data:
              page_type: components
              components:
                - type: text
                  content: 1
                  position:
                    - 0
                    - 0
                  font: pico_8
                  color: white
          target:
            device_id: b90993533d7a83d58f252c3b58e171e0
        - delay:
            hours: 0
            minutes: 0
            seconds: 5
            milliseconds: 0
        - service: divoom_pixoo.show_message
          metadata: {}
          data:
            page_data:
              page_type: components
              components:
                - type: text
                  content: 2
                  position:
                    - 0
                    - 0
                  font: pico_8
                  color: red
          target:
            device_id: b90993533d7a83d58f252c3b58e171e0
        - delay:
            hours: 0
            minutes: 0
            seconds: 5
            milliseconds: 0
mode: restart
fields: {}
icon: mdi:book-open-page-variant
```

The Loop starter **automation** (executes at HA's launch):
```yaml
alias: Start Pixoo's Page Rotation Loop
description: Only runs at the start of HA.
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.1711740597910
mode: single
```

And finally, an example of how you can make notifications using an **automation**.
(You can set the trigger to whatever fits your use)
```yaml
alias: Notification Example
description: ""
trigger: []
condition: []
action:
  - service: script.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: script.1711740597910
  - service: divoom_pixoo.show_message
    metadata: {}
    data:
      page_data:
        page_type: components
        components:
          - type: text
            position:
              - 5
              - 16
            color: red
            content: Notification!
            font: pico_8
    target:
      device_id: b90993533d7a83d58f252c3b58e171e0
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.1711740597910
mode: single
```
