### DISCUSSION TITLE
image tag for special pages

### DISCUSSION THREAD

**Discussion by gickowtf** [gickowtf/pixoo-homeassistant#57] [Ideas]
i'm in the process of incorporating the image tag from the components into the special pages. or for the progressbar so that a pictogram can be displayed where there is a lot of space. i had first thought of outsourcing everything. but now i'm more of the opinion to make a special method only for the special pages and then to deal with special tags. As an example, I would use the following "tag" for solar energy on the PV page:
sun_image_data/path/url so the size and position is not needed here because it is fixed. for the progressbar image the size and position would still be possible but as I said only conditionally possible... predefined special pages for less creative users but still largely configurable are really complicated. i'm still not quite sure how to solve this but i don't really want to redefine everything for every special page. but when i think about it i almost can't avoid it.

**Comment by SB2DD** [comment]
I have an idea. Maybe that instead of adding new tags and such to the current PV page, we could recreate it using components and share it. Therefore, if users want to customize it in a deeper way, they can do so as they wish!

**Reply by SB2DD** [reply]
Done. (Here, input_number.kml is used everywhere, but the order of the numbers/texts is top to bottom (except for the time))

```yaml
page_type: components
components:
  - type: image
    image_path: /config/custom_components/divoom_pixoo/img/sunpower.png
    position: [2,1]
  - type: text
    content: "{{ states('input_number.kml') }}"
    color: "{{ [255,175,0] if states('input_number.kml')|int >= 1 else [131,131,131] }}"
    font: GICKO
    position: [17,8]
  - type: image
    image_path: "{{ '/config/custom_components/divoom_pixoo/img/akku80-100.png' if states('input_number.kml')|int >= 80 else '/config/custom_components/divoom_pixoo/img/akku60-80.png' if states('input_number.kml')|int >= 60 else '/config/custom_components/divoom_pixoo/img/akku40-60.png' if states('input_number.kml')|int >= 40 else '/config/custom_components/divoom_pixoo/img/akku20-40.png' if states('input_number.kml')|int >= 20 else '/config/custom_components/divoom_pixoo/img/akku00-20.png'}}"
    position: [2, 17]
  - type: text
    content: "{{ states('input_number.kml') }}"
    color: "{{ [255,0,68] if states('input_number.kml')|int <= 0 else [4,204,2] }}"
    font: GICKO
    position: [17, 18]
  - type: text
    content: "{{ states('input_number.kml') }}%"
    color: white
    font: PICO_8
    position: [17, 25]
  - type: image
    image_path: "/config/custom_components/divoom_pixoo/img/haus.png"
    position: [2,33]
  - type: text
    content: "{{ states('input_number.kml') }}"
    color: [0,123,255]
    font: GICKO
    position: [17, 40]
  - type: image
    image_path: "/config/custom_components/divoom_pixoo/img/industry.png"
    position: [2,49]
  - type: text
    content: "{{ states('input_number.kml') }}"
    color: [131,131,131]
    font: GICKO
    position: [17, 56]
  - type: text
    content: "{{ now().strftime('%H:%M') }}"
    color: white
    font: PICO_8
    position: [44, 1]
```

_(This does really make me want to introduce a "variables" tag for the components page, which could be used in templates...)_
