### DISCUSSION TITLE
Using Pixoo 64 as Spotify album artwork display

### DISCUSSION THREAD

**Discussion by GuySie** [gickowtf/pixoo-homeassistant#72] [Show and tell]
Thanks for your integration! I'm using it to show the currently playing song's album art on the Pixoo display, similar to a [Tuneshine](https://www.tuneshine.rocks/). The Tuneshine looks much prettier as a home deco object, with its wood finish and all, but I figured it would be a ton of fun to build something similar in Home Assistant. Your integration made it super easy.

![flaminglips](https://github.com/gickowtf/pixoo-homeassistant/assets/3367490/12fc41e8-b5ce-4f27-a4b3-ff6fbf949f82)

It's very cool to see album art I know very well in this abstract, almost pixel-art style. I'm using the Spotify integration to listen to changes in my Spotify account, then when the track ID changes I send the current coverart to the Pixoo using the 'Send a page to Divoom Pixoo' service call. The following page data works fine for me:

```
page_type: components
components:
  - type: image
    height: 64
    width: 64
    resample_mode: lanczos
    image_url: >-
      http://homeassistant.local:8123{{
      state_attr('media_player.spotify', 'entity_picture') }}
    position:
      - 0
      - 0
```

The nice thing about using the Spotify integration for this, is that it will work when we're playing music from an interface/app other than Home Assistant/Music Assistant. It connects to your Spotify account, not a specific media player, so the display will show art even if we're using the Spotify phone app, or listening from a smart TV app. 

The disadvantage is that Home Assistant's Spotify integration is cloud polling, and updates only about every 30 seconds. So there can be up to 30 seconds of delay before the art updates after a song change. If you're only using Home Assistant as your media interface, I think there would probably be better (read: updated faster) sources of song info and coverart to tap into.

![darkside](https://github.com/gickowtf/pixoo-homeassistant/assets/3367490/45ed01e5-fa36-4c7f-9e04-7db62119bc82)

**Comment by matyonet** [comment]
I just had to reply to this... YOU ROCK!! I took your YAML config and just changed the media player over to my Plex instance and it shows the poster for whatever I play! TV shows, movies, music, you name it! This is awesome!

**Comment by pawcza** [comment]
That's awesome! I was working on something similar and just saw your post. I actually went all out and added the artist name and current music progress bar as well.

https://github.com/user-attachments/assets/65457811-dcd7-463f-b40c-f23f4216d3d9

 If anyone is interested:
 
```
- components:
    - type: image
      image_url: >-
        https://<your-ha>{{
        states.media_player.spotify.attributes.entity_picture }}
      position:
        - 0
        - 0
    - type: rectangle
      position:
        - 0
        - 0
      size:
        - 64
        - 8
      color: black
    - color: white
      content: "{{states('input_text.spotify_scrolling_artist')}}"
      font: PICO_8
      position:
        - 0
        - 1
      type: text
    - type: rectangle
      position:
        - 0
        - 56
      size:
        - 64
        - 8
      color: black
    - color: white
      content: "{{states('input_text.spotify_scrolling_title')}}"
      font: PICO_8
      position:
        - 0
        - 57
      type: text
    - color: dimgray
      filled: true
      type: rectangle
      size:
        - 64
        - 1
      position:
        - 0
        - 55
    - color: green
      filled: true
      type: rectangle
      size:
        - "{{ states('input_number.spotify_song_progress') }}"
        - 1
      position:
        - 0
        - 55
  page_type: components
```

Automation for scrolling artist / title:

```
alias: Spotify - Scroll Artist
description: ""
triggers:
  - trigger: time_pattern
    seconds: /1
conditions:
  - condition: state
    entity_id: media_player.spotify
    state: playing
actions:
  - action: input_text.set_value
    metadata: {}
    data:
      value: >
        {% set title = state_attr('media_player.spotify', 'media_artist')
        | replace(' ', "'") | replace('&', '@') or "Unknown Artist" %} {% set
        full_text = (title + "|") * 10 %}  {# Repeat more times to ensure
        continuous scrolling #} {% set full_length = full_text | length %} {%
        set ticks = now().second % full_length %} {% if ticks + 17 > full_length
        %}
            {{ full_text[ticks:] + full_text[:(ticks + 17) % full_length] }}
        {% else %}
            {{ full_text[ticks:ticks+17] }}
        {% endif %}
    target:
      entity_id: input_text.spotify_scrolling_artist
mode: single
```

^ do similar for Scrolling Title

Automation for the progress bar (due to spotify integration only doing a request every 30 seconds or so it starts calculating up every second until it receives an update):

```
alias: Spotify - Update Song Progress Every Second
description: ""
triggers:
  - seconds: /1
    trigger: time_pattern
conditions:
  - condition: state
    entity_id: media_player.spotify
    state: playing
actions:
  - data:
      entity_id: input_number.spotify_song_progress
      value: >
        {% set duration = state_attr('media_player.spotify',
        'media_duration') | float(1) %} {% set position =
        state_attr('media_player.spotify', 'media_position') | float(0)
        %} {% set last_update = state_attr('media_player.spotify',
        'media_position_updated_at').timestamp() %} {% set now_time =
        now().timestamp() %}

        {% set estimated_position = position + (now_time - last_update) %} {% if
        estimated_position > duration %} {% set estimated_position = duration %}
        {% endif %}

        {% set progress = (estimated_position / duration) * 64 if duration > 0
        else 0 %} {{ progress | round }}
    action: input_number.set_value
mode: restart
```

You need to set-up Helpers: 
* input_text.spotify_scrolling_artist
* input_text.spotify_scrolling_title
* input_number.spotify_song_progress
