### DISCUSSION TITLE
New pages request

### DISCUSSION THREAD

**Discussion by p1ranha** [gickowtf/pixoo-homeassistant#85] [Ideas]
Hi, I just found out your awesome integration! 

I was about to throw my pixoo 64 to trash, and get lametric or something similar to get notifications out of HA. I also noticed the new Ulanzi [Review](https://www.youtube.com/watch?v=jQy8D_eXoKY&pp=ygUGdWxhbnpp) which seems very solid notification system.

But since I have Pixoo and your great integration, would that be possible to get few basic pages allowing us for easier use of it?

Would it be possible to have below components built in?
a) notification page: a page with a title, icon/gif (either base64, or remote or local), and the multiline text (centered)? Optionally sound option.
b) weather page similar to weather one,  having a one line of text at the bottom that would be scrolling (similar to status in fuel)

Also I think it would be really beneficial if you'd allow easy way of sharing designs by other people. That helps newbies like me :)

Having few blueprints with variables, and ability for the component to act as notification service of HA would be the dream.

**Comment by entrhopi** [comment]
Hi!

I have created a page similar to 'Weather One" but it will only work with the upcoming alignment pull request #98 
I've also omitted the current weather section to display Home Assistant messages. And there are some weather icons missing. I may create another PR for those in the future.

Anyway, here is the code for that:

```
- components:
    - align: center
      content: |-
        Test
        Multiline
        Another <>
        ?:;.,
      position:
        - 33
        - 11
      type: text
    - color: grey
      content: "{{ date }}"
      position:
        - 2
        - 2
      type: text
    - align: center
      content: "{{ time }}"
      position:
        - 33
        - 2
      type: text
    - align: right
      color: cornflowerblue
      content: "{{ day }}"
      position:
        - 62
        - 2
      type: text
    - color: grey
      position:
        - 2
        - 9
      size:
        - 60
        - 1
      type: rectangle
    - color: grey
      position:
        - 2
        - 35
      size:
        - 60
        - 1
      type: rectangle
    - align: center
      content: >-
        {{ (as_timestamp(state_attr('sensor.daily_weather',
        'forecast')[0].datetime) | timestamp_custom('%a'))[:2] }}
      position:
        - 6
        - 37
      type: text
    - align: center
      content: >-
        {{ (as_timestamp(state_attr('sensor.daily_weather',
        'forecast')[1].datetime) | timestamp_custom('%a'))[:2] }}
      position:
        - 23
        - 37
      type: text
    - align: center
      content: >-
        {{ (as_timestamp(state_attr('sensor.daily_weather',
        'forecast')[2].datetime) | timestamp_custom('%a'))[:2] }}
      position:
        - 39
        - 37
      type: text
    - align: center
      content: >-
        {{ (as_timestamp(state_attr('sensor.daily_weather',
        'forecast')[3].datetime) | timestamp_custom('%a'))[:2] }}
      position:
        - 56
        - 37
      type: text
    - image_path: >-
        /config/custom_components/divoom_pixoo/img/weather/{{
        state_attr('sensor.daily_weather', 'forecast')[0].condition }}.png
      position:
        - 3
        - 43
      type: image
    - image_path: >-
        /config/custom_components/divoom_pixoo/img/weather/{{
        state_attr('sensor.daily_weather', 'forecast')[1].condition }}.png
      position:
        - 20
        - 43
      type: image
    - image_path: >-
        /config/custom_components/divoom_pixoo/img/weather/{{
        state_attr('sensor.daily_weather', 'forecast')[2].condition }}.png
      position:
        - 36
        - 43
      type: image
    - image_path: >-
        /config/custom_components/divoom_pixoo/img/weather/{{
        state_attr('sensor.daily_weather', 'forecast')[3].condition }}.png
      position:
        - 52
        - 43
      type: image
    - align: center
      color: sandybrown
      content: >-
        {{ state_attr('sensor.daily_weather', 'forecast')[0].temperature | round
        }}°
      position:
        - 6
        - 52
      type: text
    - align: center
      color: lightgrey
      content: >-
        {{ state_attr('sensor.daily_weather', 'forecast')[1].temperature | round
        }}°
      position:
        - 23
        - 52
      type: text
    - align: center
      color: lightgrey
      content: >-
        {{ state_attr('sensor.daily_weather', 'forecast')[2].temperature | round
        }}°
      position:
        - 39
        - 52
      type: text
    - align: center
      color: lightgrey
      content: >-
        {{ state_attr('sensor.daily_weather', 'forecast')[3].temperature | round
        }}°
      position:
        - 56
        - 52
      type: text
    - align: center
      color: lightskyblue
      content: "{{ state_attr('sensor.daily_weather', 'forecast')[0].templow | round }}°"
      position:
        - 6
        - 58
      type: text
    - align: center
      color: darkgrey
      content: "{{ state_attr('sensor.daily_weather', 'forecast')[1].templow | round }}°"
      position:
        - 23
        - 58
      type: text
    - align: center
      color: darkgrey
      content: "{{ state_attr('sensor.daily_weather', 'forecast')[2].templow | round }}°"
      position:
        - 39
        - 58
      type: text
    - align: center
      color: darkgrey
      content: "{{ state_attr('sensor.daily_weather', 'forecast')[3].templow | round }}°"
      position:
        - 56
        - 58
      type: text
  page_type: components
  variables:
    date: "{{ now().strftime('%d.%m') }}"
    day: "{{ now().strftime('%a') }}"
    power: "{{ states.sensor.plus1pmpv_switch_0_power.state }}"
    storage: "{{ states.sensor.victron_system_battery_soc.state }}"
    time: "{{ now().strftime('%H:%M') }}"
```
