### DISCUSSION TITLE
Show only one page?

### DISCUSSION THREAD

**Discussion by michaelothomas** [gickowtf/pixoo-homeassistant#88] [Q&A] [answered]
I've successfully built a page to show on my pixoo64. However, it's still cycling through old pages? I have a configuration with one page which I have saved multiple times and it appears to be cycling through old versions. Which leads me to believe that there is some fixed number of pages somewhere. But I don't understand how to control this. :/

My config:

```
- page_type: components
  components:
    - type: image
      position:
        - 0
        - 0
      image_data: >-
        (big blob of data I won't post here)
      resample_mode: box
      height: 64
    - type: text
      content: "Trump: {{ states('sensor.trump') }}%"
      position:
        - 0
        - 20
      font: PICO_8
      color:
        - 204
        - 36
        - 26
    - type: text
      content: "Harris: {{ states('sensor.harris') }}%"
      position:
        - 0
        - 30
      font: PICO_8
      color:
        - 50
        - 85
        - 164
```
