### DISCUSSION TITLE
New Stand for Divoom Pixoo 64 – A Stable Upgrade

### DISCUSSION THREAD

**Discussion by gickowtf** [gickowtf/pixoo-homeassistant#92] [Show and tell]
Hi everyone,

For those of you who, like me, use a 3D printer alongside the Divoom Pixoo 64 as part of your setup, I’ve designed a new stand that replaces the small, unstable original holder. If you’re displaying useful information from your 3D printer, such as status updates or completion times, a stable display is essential—and this stand provides exactly that.

This stand is also a great fit for anyone using my Pixoo-HomeAssistant integration, which lets you display real-time details like your BambuLab printer’s current layer and estimated completion time directly on the Pixoo 64.

If you’re a 3D printing enthusiast and find this helpful, I would really appreciate your support with a boost! Your support helps me continue developing and refining these kinds of projects.

-> https://makerworld.com/de/models/693069#profileId-621785

Feel free to reach out if you have any feedback or questions. Thanks for checking it out!

![IMG_9615-1](https://github.com/user-attachments/assets/06716d5c-1651-48ea-9e01-aaacadb52f60)

For displaying BambuLab data, this integration is recommended: https://github.com/greghesp/ha-bambulab.

```yaml
- page_type: components
  enabled: >-
    {% if is_state('SENSOR PRINT STATUS', 'running') %} true {%
    else %} false {% endif %}
  variables:
    layer: "{{states('SENSOR CURRENT LAYER')}}"
    all_layer: "{{ states('SENSOR ALL LAYERS') }}"
    percent: "{{ states('SENSOR PERCENT') }}"
    time: "{{ now().strftime('%H:%M') }}"
    footer: "{{ states.SENSOR COMPLITION TIME.state[11:16] }}"
    # icon in base64
    icon: "{{
      'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAAEs2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpQaXhlbFhEaW1lbnNpb249IjIwIgogICBleGlmOlBpeGVsWURpbWVuc2lvbj0iMjAiCiAgIGV4aWY6Q29sb3JTcGFjZT0iMSIKICAgdGlmZjpJbWFnZVdpZHRoPSIyMCIKICAgdGlmZjpJbWFnZUxlbmd0aD0iMjAiCiAgIHRpZmY6UmVzb2x1dGlvblVuaXQ9IjIiCiAgIHRpZmY6WFJlc29sdXRpb249IjcyLzEiCiAgIHRpZmY6WVJlc29sdXRpb249IjcyLzEiCiAgIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiCiAgIHBob3Rvc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIKICAgeG1wOk1vZGlmeURhdGU9IjIwMjQtMTAtMDlUMTA6Mjk6NDArMDI6MDAiCiAgIHhtcDpNZXRhZGF0YURhdGU9IjIwMjQtMTAtMDlUMTA6Mjk6NDArMDI6MDAiPgogICA8eG1wTU06SGlzdG9yeT4KICAgIDxyZGY6U2VxPgogICAgIDxyZGY6bGkKICAgICAgc3RFdnQ6YWN0aW9uPSJwcm9kdWNlZCIKICAgICAgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWZmaW5pdHkgRGVzaWduZXIgMS4xMC44IgogICAgICBzdEV2dDp3aGVuPSIyMDI0LTEwLTA5VDEwOjI5OjQwKzAyOjAwIi8+CiAgICA8L3JkZjpTZXE+CiAgIDwveG1wTU06SGlzdG9yeT4KICA8L3JkZjpEZXNjcmlwdGlvbj4KIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cjw/eHBhY2tldCBlbmQ9InIiPz5ZQcpDAAABgGlDQ1BzUkdCIElFQzYxOTY2LTIuMQAAKJF1kc8rRFEUxz8zaPyMsLCweGlYzWhQYqOMhJKmMcqvzZtnfqh54/XeSLJVtooSG78W/AVslbVSRErWsyY2TM95nppJ5tzOPZ/7vfec7j0XvLGMpluVIdCzOTM6FlZm5+YVX55aavDhp1nVLGM4EpmkrH084HHiXdCpVf7cv1a3lLA08FQLD2mGmRMeF55cyxkO7wq3aml1SfhcOGDKBYXvHT3uct7hlMtfDpux6Ah4m4SVVAnHS1hLm7qwvBy/nlnVfu/jvKQ+kZ2Zltgh3o5FlDHCKEwwygj99DAocz9BeumWFWXyQz/5U6xIriazwTomy6RIkyMg6qpUT0hMip6QkWHd6f/fvlrJvl63en0Yql5s+60TfDtQ2Lbtz2PbLpxAxTNcZYv5K0cw8C76dlHzH0LjJlxcF7X4HlxuQduToZrqj1Qh7k0m4fUMGuag5RZqF9ye/e5z+gixDfmqG9g/gC4537j4DSxWZ8u8SvLNAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAZUlEQVQ4jWNkuGXCwMDwX/U0AwZgvG2KX4oJU4J4MKoZG4AELPk2M942xWoEYc3weMY0ggWXVZj6IYLIUuia8fgQ2Qh0zciimOqwSrGg6cSaknEBhM0kaYMAJrJ1Mgzu5DkoNQMAdiwlpo+uMv4AAAAASUVORK5CYII='
      }}"
  components:
  - type: rectangle
    position: [0,0]
    size: [64, 64]
    color: [0, 218, 52]
  - type: rectangle
    position: [0, 0]
    size: [64, 7]
    color: [51, 51, 51]
  - type: rectangle
    position: [0, 57]
    size: [64, 10]
    color: [51, 51, 51]
  - type: text
    content: "L: {{ layer }} - {{ all_layer }}"
    color: white
    font: FIVE_PIX
    position: [5, 1]
  - type: text
    content: "{{ time }}"
    color: [51, 51, 51]
    font: CLOCK
    position: [15, 10]
  - type: rectangle
    position: [2, 25]
    size: [60, 9]
    color: [51, 51, 51]
  - type: rectangle
    position: [3, 26]
    size: ["{{ 58/100 * percent | int }}", 7]
    color: red
  - type: text
    content: "{{ percent }}%"
    color: white
    font: PICO_8
    position: [5, 27]
  - type: text
    content: "Ready at: {{ footer }}"
    color: white
    font: FIVE_PIX
    position: [5, 58]
  - type: image
    position: [22, 35]
    image_data: "{{ icon }}"
    resample_mode: box
    height: 20

```
