### DISCUSSION TITLE
Configuration questions

### DISCUSSION THREAD

**Discussion by hphd70** [gickowtf/pixoo-homeassistant#99] [Q&A] [answered]
Hi,
First: a really big thank for this awesome integration!!
I successfully created some pages displaying information like wheater, last 12 hour weather values, solar, spotify and played around with different clocks ;-)

I have some issues I do not know how to solve them:
- is there a way to enter remarks in the configuration? as soon I enter "##" at the beginning of a line, the line will be deleted after I saved the config.
- is there a way to call a specific page as soon a sensor will be changed? One page displays the spotify information of the the currently played song (picture, media_artist , media_title). I want that this specific page will be displayes as soon the song changes regardless if another pages is displayed. 
- is it possible to name a page? Depending on which page is displayed I will refresh the page using an automation which calls the "update_page" function. At the moment my automation looks like this:
```
alias: Divoom refresh
description: ""
triggers:
  - seconds: /15
    trigger: time_pattern
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.divoom_pixoo_64_current_page
        state: "2"
      - condition: state
        entity_id: sensor.divoom_pixoo_64_current_page
        state: "1"
      - condition: state
        entity_id: sensor.divoom_pixoo_64_current_page
        state: "8"
      - condition: state
        entity_id: sensor.divoom_pixoo_64_current_page
        state: "9"
actions:
  - action: divoom_pixoo.update_page
    metadata: {}
    data: {}
mode: single
```
when I want to reorder the pages in the configuration, I have to change the page numbers in the automation, a name would be easier.

- is it possible to have a wider config window for the integration, or is this a home assistant issue?

Thanks and best regards

**Comment by gickowtf** [comment]
First of all, thank you very much, the problem with the comment and the narrow configuration window are both problems of HomeAssistant itself! As a workaround, I have stored a separate config pixoo.yaml which I then edit in VSCode and then copy and paste into the config of the Pixoo!

I'm not sure about your problem with Spotify - you should be able to react to attribute changes! 

Unfortunately, it is not possible to name a page because the YAML code is ultimately a list [0, 1, 2, 3....] 
I hope I was still able to help you.

**Comment by hphd70** [comment]
Thanks a lot for your answer!
I already react to Spotify attribute changes. What I planned to do is to activate a specific page after the attribute changed. Is it possible to show this specific page? Something like set current_page

**Comment by gickowtf** [comment, marked as answer]
Oh well... well then take a look at this automation:
```yaml
alias: YOUR AUTOMATION
description: ""
mode: single
triggers:
 YOUR TRIGGER WITH SPOTIFY ATTRIBUTES
conditions: []
actions:
  - data:
      duration: 30
      page_data:
        page_type: components
        components:
          - type: text
            content: |-
             YOUR TITLE
            color: white
            font: gicko
            position:
              - 5
              - 1
    target:
      entity_id: sensor.divoom_pixoo_64_current_page
    action: divoom_pixoo.show_message
```
In this case, the page configured here would be displayed “immediately” for 30 seconds when the title is changed

**Comment by hphd70** [comment]
many thanks for your answer!
In principal it works... but there is a problem with my automation which refrehes some pages (code above). A soon this automation will be fired, the message will dissapear.
I found another way to achieve my request:
I put the following code as 1st page in the configruation and created a new automation which will be triggered by the Spotify attribute and reloads the pixoo integration -> the 1st page will be displayed

```
- components:
    - height: 64
      image_url: >-
        http://myHA:8123{{ state_attr('media_player.spotify', 'entity_picture') }} 
      position:
        - 0
        - 0
      resample_mode: box
      type: image
      width: 64
    - color: lightgreen
      content: |-
        {{ media_artist }} 
        {{ media_title[:15] }} 
        {{ media_title[15:30] }}         
      font: pico_8
      position:
        - 2
        - 1
      type: text
  enabled: >-
    {{ (is_state('sensor.onkyo_media_content_id','spotify') and is_state('media_player.onkyo_avr','playing')) }} 
  page_type: components
  variables:
    media_artist: >-
      {{ state_attr('media_player.spotify','media_artist') |replace('ä','ae', 1) | replace('ö','oe', 1) | replace('ü','ue', 1)}}     
    media_title: >-
      {{ state_attr('media_player.spotify','media_title') | replace('ä','ae', 1) | replace('ö','oe', 1) | replace('ü','ue', 1)}}     

```

thanks again and have a good start in 2025!
