### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by KrX3D** [gickowtf/pixoo-homeassistant#4]
Hello,

it would be nice to have more options like brigthness and so on.

till now i used this:

configuration.yaml:
```
rest_command:
  # http://doc.divoom-gz.com/web/#/12?page_id=196
  pixoo64_set_brightness:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Channel/SetBrightness", "Brightness":{{ brightness }}}'
    content_type: "application/json; charset=utf-8"
  pixoo64_switch_off:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Channel/OnOffScreen", "OnOff":0}'
    content_type: "application/json; charset=utf-8"
  pixoo64_switch_on:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Channel/OnOffScreen", "OnOff":1}'
    content_type: "application/json; charset=utf-8"
  pixoo64_set_channel:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Channel/SetIndex", "SelectIndex":{{ effect }}}'
    content_type: "application/json; charset=utf-8"
  pixoo64_set_custom_channel_page:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Channel/SetCustomPageIndex", "CustomPageIndex":{{ page }}}'
    content_type: "application/json; charset=utf-8"
  pixoo64_set_text:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Draw/SendHttpText", "TextId":{{ id }}, "x":0, "y":{{ y }}, "dir":0, "font":{{ font }}, "TextWidth":64, "speed":{{ speed }}, "TextString":"{{ text }}", "color":"{{ color }}", "align":2}'
    content_type: "application/json; charset=utf-8"
  pixoo64_reset_gif:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Draw/ResetHttpGifId"}'
    content_type: "application/json; charset=utf-8"
  pixoo64_send_gif:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Draw/SendHttpGif", "PicNum":1, "PicWidth":64, "PicOffset":0, "PicID":0, "PicSpeed":100, "PicData":"{{ gif }}"}'
    content_type: "application/json; charset=utf-8"
  pixoo64_play_buzzer:
    url: !secret pixoo_post_address
    method: POST
    payload: '{"Command":"Device/PlayBuzzer", "ActiveTimeInCycle":500, "OffTimeInCycle":500, "PlayTotalTime":500}'
    content_type: "application/json; charset=utf-8"
```

and lights.yaml:

```
#https://community.home-assistant.io/t/divoom-pixoo-64/420660
- platform: template
  lights:
    pixoo64:
      friendly_name: "Wohnzimmer - Pixoo"
      unique_id: pixoo64
      level_template: "{{ ( state_attr('sensor.pixoo64_data', 'Brightness') * 2.55 ) | round(0) | int  }}"
      value_template: "{{ state_attr('sensor.pixoo64_data', 'LightSwitch')|int == 1 }}"
      effect_list_template: "{{['Faces', 'Cloud Channel', 'Visualizer', 'Custom']}}"
      effect_template: "{{ states('sensor.pixoo64_current_channel') }}"
      turn_on:
        service: rest_command.pixoo64_switch_on
      turn_off:
        service: rest_command.pixoo64_switch_off
      set_level:
        service: rest_command.pixoo64_set_brightness
        data:
          brightness: "{{ ( brightness / 2.55 ) | round(0) | int }}"
      set_effect:
        - service: rest_command.pixoo64_set_channel
          data:
            effect: >-
              {% if effect == 'Faces' %}
              0
              {% elif effect == 'Cloud Channel' %}
              1
              {% elif effect == 'Visualizer' %}
              2
              {% else %}
              3
              {% endif %}
```

but somehow after some days ic ant reach the device and i need to restart it.

i posted some links maybe they can help.

Thanks
