### ISSUE TITLE
"Duration" from a variable

### ISSUE THREAD

**Issue by hphd70** [gickowtf/pixoo-homeassistant#70]
I am struggling around with following issue:
I want to define the duration of the pages with a input_number.

I cannot get this work.

`duration: "{{ states('input_number.divoom_duration') }}"`

With the following code the value of the variable will be displayed:
```
- type: text
  content: "{{ states('input_number.divoom_duration') }}"
  font: five_pix
  position:
	- 1
	- 1
	
```
But as soon I enter the duration part the page will not be displayed

What I am doing wrong?
