### ISSUE TITLE
Components page

### ISSUE THREAD

**Issue by wallb35** [gickowtf/pixoo-homeassistant#93]
Hello, my componenent page dosent display anything since last update. Any idea ?

```
- page_type: components
  duration: 7
  components:
    - type: image
      position:
        - 0
        - 0
      image_path: >-
        /config/custom_components/divoom_pixoo/img/house_{{states('sensor.season')}}.png
    - type: text
      position:
        - 21
        - 10
      content: >-
        {{
        states('sensor.weather_station_weather_station_weather_station_nomade_temperature')
        | round(1) }} °C
      font: gicko
      color: gray
    - type: text
      position:
        - 10
        - 30
      content: "{{ states('sensor.salon_temperature') | round(1) }} °C"
      font: gicko
      color: coral
    - type: text
      position:
        - 20
        - 52
      content: >-
        {{
        states('sensor.weather_station_weather_station_weather_station_outdoor_module_temperature')
        | round(1) }} °C
      font: gicko
      color: aqua
```
